// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJmoPLyAj9vGw6U8l3HvJMjfpHD6rD6J4',
    appId: '1:486657401255:web:ddb840e8914b00b83a5682',
    messagingSenderId: '486657401255',
    projectId: 'mess-48bb5',
    authDomain: 'mess-48bb5.firebaseapp.com',
    storageBucket: 'mess-48bb5.appspot.com',
    measurementId: 'G-L7TR8FR4Y9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu0vMojQaXppGTzTEstAdiNYIRzpeWwbU',
    appId: '1:486657401255:android:96a3ac9178b687c93a5682',
    messagingSenderId: '486657401255',
    projectId: 'mess-48bb5',
    storageBucket: 'mess-48bb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_ntJwySSMop8GwBESoFpp8Zq3OAYML0k',
    appId: '1:486657401255:ios:00667dae27b09ac93a5682',
    messagingSenderId: '486657401255',
    projectId: 'mess-48bb5',
    storageBucket: 'mess-48bb5.appspot.com',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_ntJwySSMop8GwBESoFpp8Zq3OAYML0k',
    appId: '1:486657401255:ios:b26f9f034a5d42113a5682',
    messagingSenderId: '486657401255',
    projectId: 'mess-48bb5',
    storageBucket: 'mess-48bb5.appspot.com',
    iosBundleId: 'com.example.flutterApplication4.RunnerTests',
  );
}
